package models.book;

public enum Genre {
    FICTION, NON_FICTION, SCIENCE_FICTION, MYSTERY, THRILLER, ROMANCE, FANTASY,
    HORROR, BIOGRAPHY, HISTORY, CHILDREN, SCIENCE, POETRY, DICTIONARY, COMICS
}
